In [4]:
import numpy as np #Question 1 
tab=np.array([[1,2],[3,4]])
print(tab.tolist())

[[1, 2], [3, 4]]


In [12]:
#Question 2 
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
A= x[0,0]
B= x[2,2]
C = x[1,1]
Z = A + B + C
print(Z)

15


In [25]:
#Question 3 
import numpy as np
x = int(input())
a = np.array([[1,2],[3,5]])
if x>=5:
    print("No elements higher than 5")
else:
    newArr =  a[a > x]
print(newArr, "are higher than", x)

        
        



3
[5] are higher than 3


In [26]:
#Question 4 
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
C = A + B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [38]:
#Question 5 
import numpy as np
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])  
Y = A - A.mean(axis=1) #Subtracting the mean of each row from the elements; (subtracting [2,5,8]) from each row
print(Y)


[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]
